'use client';

export interface ComplaintData {
  fullName: string;
  email: string;
  address: string;
  sector: string;
  subject: string;
  description: string;
  photoUrl?: string;
}

export function generateComplaintDraft(data: ComplaintData): string {
  const sectorNames: Record<string, string> = {
    garbage: 'Garbage & Sanitation',
    electricity: 'Electricity Supply',
    water: 'Water Supply',
    roads: 'Roads & Infrastructure',
    other: 'Other',
  };

  const currentDate = new Date().toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const draft = `CIVIC COMPLAINT REGISTRATION
================================================================================

COMPLAINT ID: JM-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}
DATE OF FILING: ${currentDate}

================================================================================
COMPLAINANT INFORMATION
================================================================================

Name:                  ${data.fullName}
Email Address:         ${data.email}
Location/Address:      ${data.address}

================================================================================
COMPLAINT DETAILS
================================================================================

Category:              ${sectorNames[data.sector] || data.sector}
Subject:               ${data.subject}

Description:
${data.description}

================================================================================
STATUS
================================================================================

Status:                SUBMITTED
Date of Submission:    ${currentDate}
Expected Resolution:   Within 7-14 business days

================================================================================
NEXT STEPS
================================================================================

1. Your complaint has been registered in our system
2. An email confirmation has been sent to ${data.email}
3. Our team will review your complaint and take appropriate action
4. You will receive status updates via email
5. For urgent matters, please contact the civic authorities directly

================================================================================

This is an automatically generated complaint document. For inquiries, 
please reference your Complaint ID.

Generated by JanMitraN - Citizens Civic Portal
================================================================================`;

  return draft;
}
